# Generated by Django 2.0.5 on 2019-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='Test Django Shell, New Article, Main content.'),
            preserve_default=False,
        ),
    ]
